[package]
name = "connector"
version.workspace = true
edition.workspace = true

[[bin]]
name = "morrow-connector"
path = "src/main.rs"

[dependencies]
client.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
server.workspace = true
tempfile = "3.27.0"
