[package]
name = "integration"
version.workspace = true
edition.workspace = true

[dependencies]
client.workspace = true
serde_json.workspace = true
server.workspace = true
tokio.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true

[dev-dependencies]
wat = "1.254.0"
